{
 "title": "VPN Performace",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "ping_ms" } },
   {
    "name": "Sites",
    "query": "nyc:159.89.177.46,sfo: 164.92.114.110,fra:157.245.83.95"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "stat",
   "description": "to Speed Test Server",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_ms{instance=\"$node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SpeedTest",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "download_speed_bps{instance=\"$node\"}",
     "legendFormat": "{{ instance }} Download "
    },
    {
     "expr": "upload_speed_bps{instance=\"$node\"}",
     "legendFormat": "{{instance}} Upload"
    }
   ]
  },
  {
   "title": "IPERF Testing",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_received_bytes/iperf3_received_seconds * 8",
     "legendFormat": "{{ job }} Download to {{instance}}"
    },
    {
     "expr": "iperf3_sent_bytes/iperf3_sent_seconds * 8",
     "legendFormat": "{{ job }} Upload to {{instance}}"
    }
   ]
  },
  {
   "title": "IPERF Testing",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_received_bytes/iperf3_received_seconds * 8"
    },
    {
     "expr": "iperf3_sent_bytes/iperf3_sent_seconds * 8"
    }
   ]
  }
 ]
}