{
 "title": "VPN Performace",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "SpeedTest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "download_speed_bps{}", "legendFormat": "{{ job }} Download " },
    { "expr": "upload_speed_bps{}", "legendFormat": "{{job}} Upload" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "to Speed Test Server",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_ms{}", "legendFormat": "{{ job }} Latency " }
   ]
  },
  {
   "title": "IPERF Testing",
   "type": "timeseries",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "iperf3_received_bytes/iperf3_received_seconds * 8",
     "legendFormat": "{{ job }} Download to {{instance}}"
    },
    {
     "expr": "iperf3_sent_bytes/iperf3_sent_seconds * 8",
     "legendFormat": "{{ job }} Upload to {{instance}}"
    }
   ]
  }
 ]
}