{
 "title": "VPN Performace Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "label": "site", "query": { "query": "ping_ms" } }
  ]
 },
 "panels": [
  {
   "title": "Latency to Speedtest from $site",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_ms{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Speedtest for $site",
   "type": "bargauge",
   "description": "Measure of local Bandwidth Capability",
   "gridPos": { "h": 8, "w": 16, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "download_speed_bps{site=\"$site\"}",
     "legendFormat": "{{site}} Download from Speedtest"
    },
    {
     "expr": "upload_speed_bps{site=\"$site\"}",
     "legendFormat": "{{site}} Upload to Speedtest"
    }
   ]
  },
  {
   "title": "$site bandwidth to Remote Destinations",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(iperf3_received_bytes{job=\"$site\"}/iperf3_received_seconds{job=\"$site\"} * 8) ",
     "legendFormat": "{{ job }}  Download from {{site}}"
    },
    {
     "expr": "(iperf3_sent_bytes{job=\"$site\"}/iperf3_sent_seconds{job=\"$site\"} * 8)",
     "legendFormat": "{{ job }} Upload to {{site}}"
    }
   ]
  },
  {
   "title": "$site bandwidth to Remote Destinations",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(iperf3_received_bytes{job=\"$site\"}/iperf3_received_seconds{job=\"$site\"} * 8) ",
     "legendFormat": "{{ job }}  Download from {{site}}"
    },
    {
     "expr": "(iperf3_sent_bytes{job=\"$site\"}/iperf3_sent_seconds{job=\"$site\"} * 8)",
     "legendFormat": "{{ job }} Upload to {{site}}"
    }
   ]
  },
  {
   "title": "Site iperf to remote destinations ",
   "type": "stat",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_success",
     "legendFormat": "{{ job }} connected to {{site}}"
    }
   ]
  },
  {
   "title": "Latency to Speedtest All Servers",
   "type": "gauge",
   "description": "to Speed Test Server",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_ms{}", "legendFormat": "{{ site }}" }
   ]
  },
  {
   "title": "Speedtest Per Site",
   "type": "bargauge",
   "description": "to Speed Test Server",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed_bps{}", "legendFormat": "{{site}} Download Speed" },
    { "expr": "upload_speed_bps{}", "legendFormat": "{{site}} Upload Speed" }
   ]
  },
  {
   "title": "IPERF Testing",
   "type": "bargauge",
   "description": "Iperf Testing between Sites",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_received_bytes/iperf3_received_seconds * 8",
     "legendFormat": "{{ job }} Download from {{site}}"
    },
    {
     "expr": "iperf3_sent_bytes/iperf3_sent_seconds * 8",
     "legendFormat": "{{ job }} Upload to {{site}}"
    }
   ]
  }
 ]
}