{
 "title": "Speedtest Performance Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin",
    "label": "origin",
    "query": {
     "query": "{job=\"iperf\"}"
    }
   },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "{job=\"speedtest\"}"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "provider",
    "label": "provider",
    "query": {
     "query": "{job=\"speedtest\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Perfromance for $site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency to Speedtest from $site",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_ms{site=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$site connection to remote destinations ",
   "type": "stat",
   "gridPos": { "h": 11, "w": 17, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iperf3_success{site=\"$site\"}",
     "legendFormat": "{{ site }} connected to {{ origin }}"
    }
   ]
  },
  {
   "title": "Speedtest + IPERF Last $site ",
   "type": "bargauge",
   "description": "Measure of local Bandwidth Capability",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "download_speed_bps{site=\"$site\"}",
     "legendFormat": "{{site}} Download  {{job}} "
    },
    {
     "expr": "iperf3_received_bytes{site=\"$site\"}/iperf3_received_seconds{site=\"$site\"} * 8",
     "legendFormat": "{{ site }}  {{job}} Download from   {{ origin }}"
    },
    {
     "expr": "upload_speed_bps{site=\"$site\"}",
     "legendFormat": " {{site}} Upload  {{job}} "
    },
    {
     "expr": "iperf3_sent_bytes{site=\"$site\"}/iperf3_sent_seconds{site=\"$site\"} * 8",
     "legendFormat": "{{ site }}  {{job}} Upload from   {{ origin }}"
    }
   ]
  },
  {
   "title": "Speedtest + IPERF Last $site ",
   "type": "timeseries",
   "description": "Measure of local Bandwidth Capability",
   "gridPos": { "h": 15, "w": 12, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "download_speed_bps{site=\"$site\"}",
     "legendFormat": "{{site}} Download  {{job}} "
    },
    {
     "expr": "iperf3_received_bytes{site=\"$site\"}/iperf3_received_seconds{site=\"$site\"} * 8",
     "legendFormat": "{{ site }}  {{job}} Download from   {{ origin }}"
    },
    {
     "expr": "upload_speed_bps{site=\"$site\"}",
     "legendFormat": " {{site}} Upload  {{job}} "
    },
    {
     "expr": "iperf3_sent_bytes{site=\"$site\"}/iperf3_sent_seconds{site=\"$site\"} * 8",
     "legendFormat": "{{ site }}  {{job}} Upload from   {{ origin }}"
    }
   ]
  }
 ]
}